name: @pluginName@
version: @version@
main: @group@.@pluginname@.@pluginName@
api-version: 1.13
authors: [HalfOf2]
commands:
  test:
    description: places a test block
    usage: /test
    aliases: [t]
    permission: asyncore.test